<?php

namespace Neoan3\Component\Login;

use Neoan3\Core\RouteException;
use Neoan3\Frame\Demo;
use Neoan3\Model\User\UserModel;

/**
 * Class LoginController
 * @package Neoan3\Component\Login
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class LoginController extends Demo{

    /**
    * GET: api.v1/login
    * GET: api.v1/login/{id}
    * GET: api.v1/login?{query-string}
    * @param string|null $id
    * @param array $params
    * @return array
    */
    function getLogin(?string $id = null, array $params = []): array
    {
        $this->Auth->restrict();
        UserModel::init($this->provider);
        return UserModel::create($params);
    }

    /**
     * POST: api.v1/login
     * @param $body
     * @return array
     */
    function postLogin(array $body): array
    {
        UserModel::init($this->provider);
        $user = UserModel::login($body);
        if($user){
            $this->Auth->assign($user['id'],['all']);
            return $user;
        }
        throw new RouteException('Wrong Credentials',401);
    }
}
