<?php

namespace Neoan3\Component\Schedule;

use Neoan3\Frame\Demo;
use Neoan3\Model\Schedule\ScheduleModel;
use Neoan3\Provider\Model\InitModel;

/**
 * Class ScheduleController
 * @package Neoan3\Component\Schedule
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */
class ScheduleController extends Demo
{


    #[InitModel(ScheduleModel::class)]
    function getSchedule($day, $room_id, $params = [])
    {
       // $this->Auth->restrict();

        return ScheduleModel::getBookings($day, $room_id);
    }

    #[InitModel(ScheduleModel::class)]
    function postSchedule($newEntry = [])
    {
        return ScheduleModel::create($newEntry);
    }
}
