<?php

namespace Neoan3\Component\Users;

use Neoan3\Frame\Demo;
use Neoan3\Model\User\UserModel;

/**
 * Class UsersController
 * @package Neoan3\Component\Users
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class UsersController extends Demo{

    /**
    * GET: api.v1/users
    * GET: api.v1/users/{id}
    * GET: api.v1/users?{query-string}
    * @param string|null $id
    * @param array $params
    * @return array
    */
    function getUsers(?string $id = null, array $params = ["^delete_date"]): array
    {
        $this->Auth->restrict(["faculty"]);
        return $this->loadModel(UserModel::class)::find($params);
        //this function is restricted to faculty so its returns all users in the system and search for delete date to confirm the deletion
    }

    /**
     * POST: api.v1/users
     * @param null $id
     * @param array $body
     * @return array
     */
    function deleteUsers($id=null, array $body=[]): array
    {
        $this->Auth->restrict(["faculty"]);
        return $this->loadModel(UserModel::class)::delete($id);
        //this officially removes the user from the data base
    }
}
