<?php

namespace Neoan3\Component\Room;

use Neoan3\Apps\Db;
use Neoan3\Frame\Demo;
use Neoan3\Model\Room\RoomModel;

/**
 * Class RoomController
 * @package Neoan3\Component\Room
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class RoomController extends Demo{

    /**
    * GET: api.v1/room
    * GET: api.v1/room/{id}
    * GET: api.v1/room?{query-string}
    * @param string|null $id
    * @param array $params
    * @return array
    */
    function getRoom(?string $id = null, array $params = []): array
    {
        //$this->Auth->restrict();
        RoomModel::init($this->provider);
       if($id){
          return RoomModel::get($id);
            }

        $all = RoomModel::find([]);

        return $all;
    }

    /**
     * POST: api.v1/room
     * @param $body
     * @return array
     */
    function postRoom(array $body): array
    {
        $this->Auth->restrict();
        RoomModel::init($this->provider);
        return RoomModel::create($body);

    }
}
